# Generated by Django 4.0.5 on 2022-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentNumber', models.CharField(max_length=10)),
                ('facultyName', models.CharField(max_length=100)),
            ],
        ),
    ]
